region                      = "eu-west-2"
project_name                = "yourme"
environment                 = "testing"
vpc_cidr                    = "10.0.0.0/16"
public_subnet_az1_cidr      = "10.0.0.0/24"
public_subnet_az2_cidr      = "10.0.1.0/24"
private_app_subnet_az1_cidr = "10.0.2.0/24"
private_app_subnet_az2_cidr = "10.0.3.0/24"
private_db_subnet_az1_cidr  = "10.0.4.0/24"
private_db_subnet_az2_cidr  = "10.0.5.0/24"
domain_name                 = "your_domain_domain_name" #add your domain name
alternative_name            = "*.your_domain_name" # add your domain name after asterick dot.
